### PR TITLE
Redo PR #17 (merge conflict were solved incorrectly).

### PR DESCRIPTION
**Pull request by jrfnl**

### CODE REVIEW

**Comment by twoelevenjay** [comment]
did that work?

**Comment by jrfnl** [comment]
> did that work?

What do you mean ?

**Comment by twoelevenjay** [comment]
The redo did I do it right this time? Kind of in gest cuz there were no conflicts this time, but also trying to be certain I didn't mess it up this time.

**Comment by jrfnl** [comment]
Yes, looks fine now. I basically just re-created the PR based on the master after the coding standards merge, so yes, it should have merged without conflicts.

**Pull request merged**
