### PR TITLE
Feature/translation fr FR

### PR DESCRIPTION
**Pull request by Arifi**
here the french translation
enjoy :)

### CODE REVIEW

**Comment by Arifi** [comment]
Well, i just added the translation, was errored on master.. :/

**Comment by Arifi** [comment]
All works fine for me... if i could i've fixed your errors on travis...

**Comment by Arifi** [comment]
@twoelevenjay can you please give us a green (build) for this PR ?

**Comment by twoelevenjay** [comment]
Thank you very much!

**Comment by Arifi** [comment]
no problem ;)

**Pull request merged**
