### PR TITLE
Resolves issue #42 and #45

### LINKED ISSUE #42: Options 'Include a "none" option' for select field types and 'Repeatable' for all repeatable field types not working
Wordpress version: 4.8.3
CMB2 Admin Extension version: 0.1.7

Fresh wordpress install; installed and activated CMB2 plugin and CMB2 Admin Extension, downloaded from Github
Created a Meta box, with two fields. The first is a text field (text fields should be available as repeatable) and marked as repeatable. The second one is a select field with the option '_Include a "none" option_' checked. The meta box is applied to to posts.
Creating a new post, I would expect that the text field was repeatable and that would be possible to select a "_None_" option, while the text field is not repeatable and the "_None_" option is not available

In the first screenshot the metabox creation; in the second one the post creation

screenshot01

screenshot02

### PR DESCRIPTION
**Pull request by sylletka**
This commit resolves #42, which is due to an incorrect variable assignment

### CODE REVIEW

**Comment by sylletka** [comment]
Duplicate pull request

**Comment by sylletka** [comment]
This pull request is both for issue #42 and #45

**Comment by twoelevenjay** [comment]
Thank you very much for this contribution. Can you fix the PHP Code Sniffer warnings reported by Travis CI?

https://travis-ci.org/twoelevenjay/CMB2-Admin-Extension/jobs/301032070

**Comment by sylletka** [comment]
Now it should be ok

**Pull request merged**
