### PR TITLE
Portuguese (pt_PT) translation (100%)

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by twoelevenjay** [comment]
@pedro-mendonca you are great!

**Comment by pedro-mendonca** [comment]
Now the textdomain loading still needs to be corrected.

**Comment by twoelevenjay** [comment]
@pedro-mendonca , @jrfnl do either of you know how or about translating readme for wordpress.org?

https://translate.wordpress.org/projects/wp-plugins/cmb2-admin-extension

**Comment by jrfnl** [comment]
@twoelevenjay What would you like to know ?

**Comment by twoelevenjay** [comment]
Do you translate the Development readme and Stable readme in the .po files like everything else. I just noticed the columns in the link I shared mentioning them.

**Comment by jrfnl** [comment]
Basically: yes. If these are translated then localized version of the WP website, like https://pt.wordpress.org/ will display the plugin information in the native language.

All the same, I personally wouldn't bother translating the Development readme, the Stable version should be sufficient I think, but @tacoverdo might be able to advise better on this.

**Comment by pedro-mendonca** [comment]
Hi,
Usually the readmes are too long and with a lot of changelog entries that I don't bother to translate.
If the general strings in the _Description_ tab are just a few, might be interesting to have it all translated. Usually my priority goes to the plugin itself.
About stable/development, as you translate in one of the branches it goes automatically to the other.

As this readme description is really short, I'll to it in pt_PT.

**Comment by pedro-mendonca** [comment]
There are a few I left to translate because I do not totally understand the meaning. Please make it a bit more clear and please notify me again :)

**Pull request merged**
