### PR TITLE
Fix load_textdomain

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
I found a problem in this PR.
Some strings are still not loaded. Example: "CMB2 Settings" from https://github.com/twoelevenjay/CMB2-Admin-Extension/blob/master/includes/class-meta-box-settings.php#L51

The rest of "CMB2 Settings" strings are ok. I don't quite understand how, as they are on the same file.

Still, a made it work cutting the `add_action()` and `function load_textdomain()` and pasting it before the `class CMB2_Admin_Extension_Class` in https://github.com/twoelevenjay/CMB2-Admin-Extension/blob/master/cmb2-admin-extension.php#L65

**Comment by pedro-mendonca** [comment]
I've made this change: https://github.com/pedro-mendonca/CMB2-Admin-Extension/commit/236cd2a05aa8c2811b55b15337a0ea43b06cb139

Check if it's ok for you. Translations are being loaded completely now.
@jrfnl Can you help me understand why this is working better?
Regards

**Comment by twoelevenjay** [comment]
I am guessing that `add_action( 'init', array( $this, 'load_textdomain' ) );` needs to be loaded first because `$this->check_for_cmb2();` calls on functions that have gettext strings for translation. Does that make sense? @jrfnl does that sound right?

**Comment by jrfnl** [comment]
I'll have a look and get back to you, but from first glance some things which should be improved:
* text-domain *should* be loaded on the `init` action - not on `plugins_loaded` - see http://geertdedeckere.be/article/loading-wordpress-language-files-the-right-way
* the path to the language directory should be a proper full path and not have a end slash

Will get back to you once I've run some tests with the [Debug Bar Localization](https://wordpress.org/plugins/debug-bar-localization/) which should be able to pinpoint it more closely.

**Comment by jrfnl** [comment]
Ok. Debugged. I'll send in a number of pull requests which combined will fix this.

The issue was a combination of things:
* The language loading wasn't working for the admin notices as the notices weren't hooked in properly and therefore printed to the screen before the language could be loaded.
* The language loading for the CPT wasn't working as the CPT is registered on `init` prio 10 and the language loading was done on the same prio. In that case, the order is semi-random and in this case that meant the language file was loaded *after* the CPT was initialized. Setting the priority of the language loading to 9 fixes that.
* Also for some unphantomable reason something strange is going on with the `CMB2_LOADED` constant which returns the CMB2 prio and not `true` (which it is defined as), so fixed that too.

**Comment by pedro-mendonca** [comment]
Hi @jrfnl,

After I the PR https://github.com/twoelevenjay/CMB2-Admin-Extension/pull/10 all strings were loaded correctly.

Now, with this https://github.com/twoelevenjay/CMB2-Admin-Extension/pull/14 the texdomain loading was again pushed a bit further and earlier strings like https://github.com/twoelevenjay/CMB2-Admin-Extension/blob/master/includes/class-meta-box-settings.php#L51 ("CBM2 Settings") aren't loaded again.

**Comment by jrfnl** [comment]
@pedro-mendonca Hi Pedro, I'll have a look tonight when I'm back home (travelling back from WCEU at the moment) and will test it with your translation. I only added some test strings earlier to check it and it seemed fine, but I clearly missed something.
Not to worry. I'll sort it out.

**Comment by jrfnl** [comment]
@pedro-mendonca Ok, just had a good look, but basically the settings page title was being translated within the constructor (in several of the classes), assigned to a class property and then only ever used once in the class you mentioned, so I've removed the superfluous code and move the actual translating to the point of echo, that should fix it.
Will send in PR in a moment.

**Comment by pedro-mendonca** [comment]
It seems ok now :+1: 
Great :)

**Pull request merged**
