### PR TITLE
Set up Travis for automated initial code review

### LINKED ISSUE #6: Travis
Hi Leon,

I noticed you where trying to get travis working. What are the tasks you would like travis to do ?

If you like I can add a script which will work & do the following:
* lint the PHP files
* lint and hint any JS files according to the WP standards
* run PHPCS with the WP coding standards

If at some point you'd want to add unit tests to the repo as well, I can set that up too (but not before as it's useless running the test suite if you have no tests for the plugin).

Let me know if that would be helpful.

### PR DESCRIPTION
**Pull request by jrfnl**
... and make the current code base comply to the standards.

You'll probably need to turn Travis back on for it to start working. I've tested this branch on my own fork with Travis turned on and the build should pass now.

Fixes #6

The travis config:
* Lints the PHP code for parse errors.
* Lints the JS code.
* Check the PHP code against the WordPress Coding Standards.
* Check the PHP code for cross-version issues.
* Check the JS code against the WordPress Coding Standards.

Some notes on the PHP related changes I made:
* I noticed that you don't use Yoda conditions, so I've happily excluded that rule as I'm not a fan either ;-)
* I've wrapped all functions and classes within `function_exists()`/`class_exists()` wrappers.
* Changed `TODO` notes to use the PHPDoc style `@todo`
* A number of functions were/are missing proper documentation. It went a bit too far for me to write that, so I've just added a `@todo` note that documentation needs to be added and created a perfunctory docblock in those cases.
* The `$ID` variable in the `init_user_defined_meta_boxes_and_fields()` method was confusing as only moments later the variable `$id` is defined. Even though variables in PHP are case-sensitive, this was a typical situation which invites bugs, so I've renamed the first variable.

This PR will probably conflict with #17. Depending on which you merge first, I'll rebase the other to make it mergeable again.

Another thing: I've turned email notifications off. However, do be aware that also means that if you push straight to master, you won't see the result of the travis run, so you may want to turn it on.

### CODE REVIEW

**Comment by twoelevenjay** [comment]
Thank you looks great. there were some conflicts with this merge, I resolved all 3 using your versions. I hope that didn't mess anything up. I did compare files and it looked like I should be using your versions only.

**Comment by twoelevenjay** [comment]
@jrfnl I am definitly for complying with WP coding standards and will pay more attention to that. I also have been coding JS with camel case and no space padding inside of round brackets, as oppose to underscores and padding with PHP. However I am a heavy WooCommerce user and their JS is written more like PHP with underscores and extra spacing. So I was trying that approach with this project. I guess this means they don't follow coding standards in JS? This is a big surprise to me, if it is the case.

**Comment by twoelevenjay** [comment]
And I have never liked Yoda conditionals lol, is there any good argument for them?

**Comment by jrfnl** [comment]
@twoelevenjay __*Please turn on Travis as otherwise the code checks won't be run automatically.*__

> I resolved all 3 using your versions. I hope that didn't mess anything up.

Unfortunately you did, so I've submitted a PR to redo the fixes which were in #17.. It happens.

> I am definitly for complying with WP coding standards and will pay more attention to that.

Oh for sure and that showed - there weren't that many code related issues at all. Most fixes had to do with missing documentation.

> I guess this means they don't follow coding standards in JS? This is a big surprise to me, if it is the case.

Apparently they don't. Then again the WP JS CS are confusing as they are not always in line with the WP PHP CS and they were only added later, so I can see how a project would either not know about them (yet) or choose to ignore them over being consistent with the PHP CS and/or trying to minimize JS file size (though they shouldn't do that - they should just use minified files for that).

> And I have never liked Yoda conditionals lol, is there any good argument for them?

Yes - preventing accidentally assigning something to a variable within a condition, see the below code example.

Yoda conditions are mostly useful if you often use loose type comparisons or are an inexperienced programmer.
Generally speaking an experienced PHP programmer will hardly ever use loose type checks anyway so the chance of them accidentally assigning something within a condition is slim.

```php
// This would be a bug which would be hard to find:
if ( $variable = true ) {}

// If they intended the code to read like:
if ( $variable == true ) {}

// And would have been semi-prevented with Yoda conditions:
if ( true = $variable ) {} // condition is still wrong, but at least $variable is not changed
```

**Comment by twoelevenjay** [comment]
Thank you for all of that great explanation @jrfnl !

I am going to start using strict type checks :-/ lol I have accidentally assigned something to a variable within a condition a few times lol!

**Comment by twoelevenjay** [comment]
@jrfnl https://travis-ci.org/twoelevenjay/CMB2-Admin-Extension is saying it can't find a `.travis.yml` file and I can not see why. Any ideas?

**Comment by jrfnl** [comment]
If you look at the [commits it references](https://travis-ci.org/twoelevenjay/CMB2-Admin-Extension/builds), you'll see those are old ones, so these are probably checks Travis ran before you turned it off (and no back on).

It should start working properly for new commits and pull requests.

Let me have a quick look for something small to fix to test it.

**Pull request merged**
