### PR TITLE
Apply strict checking in a number of places.

### PR DESCRIPTION
**Pull request by jrfnl**
I just did a quick check in one file only. This is far from complete nor comprehensive.

Now, let's see if Travis will run...

[Edit] Yup! It's running.

### CODE REVIEW

**Comment by jrfnl** [comment]
The error Travis shows is not to do with this commit, but with the non-capitalized comment in the JS file which I pointed out to you earlier... :sunglasses:

**Comment by twoelevenjay** [comment]
Yes you did, and I missed one lol.

**Comment by jrfnl** [comment]
Happens to the best of us ;-)

**Comment by twoelevenjay** [comment]
:-) just capitalized it and the build still fails from the JS file but it appears that it is not giving a reason now.

https://travis-ci.org/twoelevenjay/CMB2-Admin-Extension/jobs/141679677

**Comment by jrfnl** [comment]
Actually - it does give the reason (just above the fail message):
https://travis-ci.org/twoelevenjay/CMB2-Admin-Extension/jobs/141679677#L255

**Comment by twoelevenjay** [comment]
Ah, I see. I imagine I can and should set up the same build testing for my dev environment?

**Comment by jrfnl** [comment]
You could try. I haven't got something like that set up myself, but you'll have to see what works for you and what you feel comfortable with.

I personally have a git `pre-commit` hook setup which will lint the PHP code just to make sure I don't commit parse errors.
And for bigger commits/feature branches I will often (manually) run them through PHPCS before pushing them to GH.
Generally speaking though, I use feature branches and send in PRs even to my own projects just to get the feedback from Travis and Scrutinizer.
I rarely commit to the master branch of any project directly (other than PR merges).

Just my two pennies. As I said before: go with what you feel will be helpful to you in your dev environment.

**Comment by twoelevenjay** [comment]
I added Atom Linter, PHPCS Linter, PHPMD Linter, and WordPress Coding Standards configs to Atom editor. Now I can see the errors as I code lol.

Should we add Scrutinizer too?

**Comment by jrfnl** [comment]
> I added Atom Linter, PHPCS Linter, PHPMD Linter, and WordPress Coding Standards configs to Atom editor. Now I can see the errors as I code lol.

:+1: 

> Should we add Scrutinizer too?

Could do. I kind of like it as it gives some indication of which areas need most improvement and sometimes catches things I missed.
The patches it gives are often wrong though and not all feedback is useful or even correct, so you have to have your head in the game when evaluating.

Would you like me to provide a config file ?

**Comment by twoelevenjay** [comment]
Hmmm, yeah I think it would be cool to try. It might make me bother you more with questions about things it catches and if they are accurate lol.

**Comment by jrfnl** [comment]
That's fine - if you like we could even set up a skype call or something to go through the initial output together.

**Comment by twoelevenjay** [comment]
Yes that sounds great!

**Comment by jrfnl** [comment]
Ok ping me on Slack to set it up ?

**Comment by twoelevenjay** [comment]
Slack? Or Skype? lol

**Comment by jrfnl** [comment]
Anywhere where we don't have to leak privacy sensitive contact details in public ;-)

**Pull request merged**
