### PR TITLE
Add missing textdomain

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by twoelevenjay** [comment]
I updated the load_textdomain, to work more like the CMB2 plugin. I ran poedit and created a pot template. So I believe that means teh textdomain is loading properly now? Sorry for my lack of knowledge. I have zero experience with localization. I am hoping to learn through this process so thank you for the help.

**Comment by jrfnl** [comment]
> Sorry for my lack of knowledge. I have zero experience with localization.

Would you like me to review and give hints & tips ?

**Comment by pedro-mendonca** [comment]
Hi @twoelevenjay,

Poedit can find every string you have in gettext functions and generate a .pot or .po file. That is the way I'm translating this plugin. But this does not mean that the .po file will be loaded, for that you need to load the textdomain correctly and give the path for .mo files, as we've been doing.

I'll check your changes to see if it's loading correctly now.

**Comment by twoelevenjay** [comment]
Thank you both of you. Yes I welcome hints and tips.

**Comment by pedro-mendonca** [comment]
I'm not sure if it's necessary a complex function like the one used by CMB2 to load textdomain.
This simple works perfectly:
https://codex.wordpress.org/Function_Reference/load_plugin_textdomain#Examples

Stil, if you want to keep it, there is a typo in it that I'll correct `$mofile = dirname( __FILE__ ) . '/languages/cmb2-admin-extension' . $locale . '.mo';`--> `'/languages/cmb2-admin-extension-'` (ending dash).
I've checked that the function is loading too late and even the file being ok, the translation isn't loaded for all strings. The ones from the included files in `private function check_for_cmb2() {` don't get translated.
Examples:
"Add New Meta Box" isn't translated, but "Metabox Settings" is translated.
I've managed to make it work inserting the `add_action( 'init', array( $this, 'load_textdomain' ) );` two lines up, before the previous `$this->check_for_cmb2();`.
I'm going to push this so you can check it.

**Comment by pedro-mendonca** [comment]
@jrfnl could you help me to understand why the not all the strings were being loaded before the second change I've made in https://github.com/twoelevenjay/CMB2-Admin-Extension/pull/10 ?

Thanks :)

**Pull request merged**
