### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
Hi @twoelevenjay 
I've been testing the localization with a file on /languages folde, but I only made it with a function to add textdomain: `load_plugin_textdomain( 'cmb2-admin-extension', false, plugin_basename( dirname( __FILE__ ) ) . '/languages' );`
Out of the box the plugin isn't getting translated.
Do you want me to push this?

**Comment by twoelevenjay** [comment]
Yes thank you.

**Comment by pedro-mendonca** [comment]
I'm not sure if it's the right place where you might want it, but I've added in the end of cmb2-admin-extension.php:

`add_action( 'plugins_loaded', 'cmb2_admin_extension_load_textdomain' );`

I'll push it and you can check if it's ok for you.

**Comment by twoelevenjay** [comment]
Ok cool

**Comment by pedro-mendonca** [comment]
Just pushed it in https://github.com/twoelevenjay/CMB2-Admin-Extension/pull/8

**Comment by twoelevenjay** [comment]
Thanks again, I did move it into the main class. Let me know if that caused
any trouble.

**Comment by pedro-mendonca** [comment]
Hi,
Yes, it broke it.
Translation isn't being loaded now.

**Comment by twoelevenjay** [comment]
Thanks for the heads up. Sorry about that. I'll fix it shortly.

**Pull request merged**
